name: Build

on:
  pull_request:
    types: opened
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install packaging dependencies
        run: pip install setuptools wheel

      - name: Build Wheel
        run: |
          pip3 install build &&
          python3 -m build

      - name: Install
        run: |
          twine check dist/* &&
          pip3 install dist/* --force-reinstall
