name: Publish on pypi

on:
  pull_request:
    - types:
      - closed
    - branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install packaging dependencies
        run: pip install setuptools wheel twine

      - name: Build Wheel
        run: |
          python3 -m build

      - name: Check wheels
        run: twine check dist/*

      - name: Publish Wheel
        run: |
          twine upload dist/* --username gogo2464 --password ${{ secrets.PYPI_GOGO2464_PASSWORD }} --verbose
